CREATE DATABASE cars;
USE cars;

SET AUTOCOMMIT = OFF;
COMMIT;
ROLLBACK;

-- READ TABLE --
SELECT * FROM cars_dekho;
-- TOTAL CARS : To get a count of total records --
SELECT COUNT(*) FROM cars_dekho;
-- THE MANAGER ASKED THE EMPLOYEE, HOW MANY CARS WILL BE AVAILABLE IN 2023? --
SELECT COUNT(*)
FROM cars_dekho
WHERE year = 2023;
-- THE MANAGER ASKED THE EMPLOYEE, HOW MANY CARS WILL BE AVAILABLE IN 2020, 2021 & 2022?
SELECT COUNT(*)
FROM cars_dekho
WHERE year IN(2020,2021,2022) GROUP BY year
ORDER BY year ; 
-- CLIENT ASKED TO PRINT THE TOTAL OF ALL CARS BY YEAR. I DON'T SEE ALL THE DETAILS. --
SELECT year, COUNT(*) AS total_cars_by_year
FROM cars_dekho
GROUP BY year ORDER BY year;
-- CLIENT ASKED TO CAR DEALER AGENT HOW MANY DIESEL CARS WILL THERE BE IN 2020? --
SELECT count(*)
FROM cars_dekho
WHERE fuel = 'Diesel' and year=2020;
-- CLIENT ASKED TO CAR DEALER AGENT HOW MANY PETROL CARS WILL THERE BE IN 2020? --
SELECT count(*)
FROM cars_dekho
WHERE fuel = 'Petrol' and year=2020;
-- THE MANAGER TOLD THE EMPLOYEE TO GIVE A LIST OF ALL THE FUEL CARS(PETROL,DIESEL & CNG) COME BY ALL YEAR. --
SELECT NAME AS cars_name,year
FROM cars_dekho
WHERE fuel IN('Petrol,Diesel','CNG');
-- MANAGER SAID THERE WERE MORE THAN 100 CARS IN A GIVEN YEAR, WHICH YEAR HAD MORE THAN 100 CARS? --
SELECT COUNT(*) AS no_of_cars ,year
FROM cars_dekho 
GROUP BY year
HAVING no_of_cars>100;
-- THE MANAGER SAID TO THE EMPLOYEE, ALL CARS COUNT DETAILS BTW 2015-2023;WE NEED A COMPLETE LIST --
SELECT COUNT(*) AS car_count,year
FROM cars_dekho
WHERE year BETWEEN 2015 AND 2023
GROUP BY year WITH ROLLUP;
-- THE MANAGER SAID TO THE EMPLOYEE, ALL CARS DETAILS BTW 2015-2023;WE NEED A COMPLETE LIST --
SELECT Name AS cars_name,year
FROM cars_dekho
WHERE year BETWEEN 2015 AND 2023;
